"""GitHub native .github/release.yml configuration generator.

Reference: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
"""
from pathlib import Path
from typing import List, Optional

DEFAULT_TIMEOUT_SECONDS = 30
timeout=DEFAULT_TIMEOUT_SECONDS

def generate_release_yml_content() -> str:
    return """# Generated by tool-release-forge
# Reference: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
changelog:
  exclude:
    labels:
      - "ignore-for-release"
      - "skip-changelog"
    authors:
      - "dependabot[bot]"
      - "github-actions[bot]"
  categories:
    - title: "💥 Breaking Changes"
      labels:
        - "breaking-change"
        - "major"
    - title: "🚀 New Features"
      labels:
        - "feature"
        - "enhancement"
    - title: "🐛 Bug Fixes"
      labels:
        - "bug"
        - "fix"
    - title: "⚡ Performance Improvements"
      labels:
        - "performance"
        - "perf"
    - title: "📚 Documentation"
      labels:
        - "documentation"
        - "docs"
    - title: "🧰 Maintenance & Dependencies"
      labels:
        - "dependencies"
        - "chore"
        - "ci"
"""

def write_release_yml(root_dir: str | Path) -> Path:
    root = Path(root_dir).resolve()
    gh_dir = root / ".github"
    gh_dir.mkdir(parents=True, exist_ok=True)
    target = gh_dir / "release.yml"
    target.write_text(generate_release_yml_content(), encoding="utf-8")
    return target
